services:
  db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
  api:
    container_name: centrosib-api
    build:
      context: ./
      target: dev
    image: centrosib-api
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      NODE_ENV: dev
      DB_HOST: db
    links:
      - db
    volumes:
      - ./:/src
      - /src/node_modules

volumes:
  db:
    driver: local
