services:
  web:
    build: .
    restart: unless-stopped
    command: sh -c "npm run migrate && npm run seed && npm run dev"
    ports:
      - 3000:3000
    env_file: .env
    depends_on:
      - db
  
  db:
    image: postgres:14.3-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
volumes:
  db-data:
